name: API HMB ALLURE

on:
  workflow_dispatch:
    inputs:
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
    ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
    ALLURE_ENDPOINT: https://testing.testops.cloud/ 
    ALLURE_PROJECT_ID: 7806
    
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
      #group: soundboard

    steps:
      - uses: ./.github/actions/dependencies
      - name: Install API dependencies
        run: cd test-components/api && npm ci
      - name: Install PW 
        run: cd test-components/api && npx playwright install
      - name: Run API PW HMB Tests
        if: success() || failure()
        run: cd test-components/api-pw/workflow-pod && npx playwright test tests/HMB --workers=1
      - name: Upload Report Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: _OUTPUT/html-report
          retention-days: 5
      - name: Upload Allure Results
        if: success() || failure()
        uses: ./.github/actions/allure
      - name: List results
        run: ls -la ${ALLURE_RESULTS}
